config:
  default: true
  MD003: false
  MD013: false
  MD022: false
  MD033:
    allowed_elements:
      - details
      - summary
      - Resource
      - model-id
      - region
      - Name
  MD024:
    siblings_only: true
  MD026: false
  MD034: false
  MD040: false
  MD041: false
  MD060: false
frontMatter: "^---\\s*$[\\s\\S]*?^---\\s*$"
