#!/usr/bin/env python3
"""Generate .cursor-plugin/marketplace.json and docs/REGISTRY.md from each
plugin's own plugin.json, so the marketplace listing can never drift out of
sync with where plugins actually live on disk.

A plugin is any directory under plugins/ that directly contains a
plugin.json, discovered at most one ecosystem folder deep (e.g.
plugins/atlassian/ or plugins/aws/aws-core/), matching the "never nest
toolkits" rule this repo follows.

Usage:
    python3 tools/generate_marketplace.py          # write both generated files
    python3 tools/generate_marketplace.py --check  # exit 1 if either is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = REPO_ROOT / "plugins"
MARKETPLACE_PATH = REPO_ROOT / ".cursor-plugin" / "marketplace.json"
REGISTRY_PATH = REPO_ROOT / "docs" / "REGISTRY.md"

MARKETPLACE_NAME = "razormetrics-cursor-plugins"
MARKETPLACE_OWNER = "RazorMetrics"
MARKETPLACE_DESCRIPTION = (
    "Cursor plugin/skill marketplace for RazorMetrics: curated, approved "
    "plugins for use across the team."
)


def find_plugin_dirs() -> list[Path]:
    """Discover plugin directories up to one ecosystem folder deep."""
    if not PLUGINS_DIR.is_dir():
        return []

    plugin_dirs = []
    for entry in sorted(PLUGINS_DIR.iterdir()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        if (entry / "plugin.json").is_file():
            plugin_dirs.append(entry)
            continue
        for sub in sorted(entry.iterdir()):
            if sub.is_dir() and (sub / "plugin.json").is_file():
                plugin_dirs.append(sub)
    return plugin_dirs


def load_plugin(plugin_dir: Path) -> dict:
    manifest = json.loads((plugin_dir / "plugin.json").read_text())
    source = plugin_dir.relative_to(REPO_ROOT).as_posix()

    mcp_servers: list[str] = []
    for mcp_name in (".mcp.json", "mcp.json"):
        mcp_path = plugin_dir / mcp_name
        if mcp_path.is_file():
            mcp_data = json.loads(mcp_path.read_text())
            mcp_servers = sorted(mcp_data.get("mcpServers", {}).keys())
            break

    skills_dir = plugin_dir / "skills"
    skill_count = 0
    if skills_dir.is_dir():
        skill_count = sum(1 for d in skills_dir.iterdir() if d.is_dir())

    return {
        "name": manifest["name"],
        "source": source,
        "description": manifest.get("description", ""),
        "mcp_servers": mcp_servers,
        "skill_count": skill_count,
    }


def render_marketplace(plugins: list[dict]) -> str:
    data = {
        "name": MARKETPLACE_NAME,
        "owner": {"name": MARKETPLACE_OWNER},
        "metadata": {"description": MARKETPLACE_DESCRIPTION},
        "plugins": [
            {
                "name": p["name"],
                "source": p["source"],
                "description": p["description"],
            }
            for p in sorted(plugins, key=lambda p: p["name"])
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def render_registry(plugins: list[dict]) -> str:
    lines = [
        "# Plugin Registry",
        "",
        "Operational index of every plugin served by this marketplace. Source of",
        "truth for availability is",
        "[`.cursor-plugin/marketplace.json`](../.cursor-plugin/marketplace.json);",
        "this file exists for humans and agents to see each plugin's scope, tools,",
        "and storage location without opening every manifest.",
        "",
        "Generated by [`tools/generate_marketplace.py`](../tools/generate_marketplace.py)"
        " — do not hand-edit. Run that script after adding, removing, or moving a"
        " plugin.",
        "",
        "| Plugin | Source path | MCP server(s) | Skills | Scope |",
        "| --- | --- | --- | --- | --- |",
    ]
    for p in sorted(plugins, key=lambda p: p["name"]):
        mcp = ", ".join(f"`{m}`" for m in p["mcp_servers"]) or "—"
        lines.append(
            f"| `{p['name']}` | [`{p['source']}`](../{p['source']}) | {mcp} "
            f"| {p['skill_count']} | {p['description']} |"
        )
    lines += [
        "",
        "## Layout conventions",
        "",
        "- Every plugin sits exactly one level deep under `plugins/`, or under a",
        "  shared ecosystem folder within `plugins/` when there is more than one",
        "  plugin for that ecosystem (e.g. `plugins/aws/<plugin>` for the AWS",
        "  plugins). Single-plugin ecosystems (e.g. `atlassian`) sit directly",
        "  under `plugins/`.",
        "- Each plugin keeps its own prompt/instruction content in a local",
        "  `skills/` subdirectory — never loose at the plugin root.",
        "- Vendored upstream projects that ship more than just plugins (canonical",
        "  skill sources, contributor tooling, docs, rules) live under",
        "  [`vendor/`](../vendor/), never under `plugins/`.",
        "- `plugins/razormetrics/` is reserved for RazorMetrics-authored plugins;",
        "  see its README for current status.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 if generated files are stale"
    )
    args = parser.parse_args()

    plugins = [load_plugin(d) for d in find_plugin_dirs()]
    outputs = {
        MARKETPLACE_PATH: render_marketplace(plugins),
        REGISTRY_PATH: render_registry(plugins),
    }

    if args.check:
        stale = []
        for path, content in outputs.items():
            current = path.read_text() if path.is_file() else None
            if current != content:
                stale.append(path.relative_to(REPO_ROOT))
        if stale:
            for path in stale:
                print(f"  STALE: {path}", file=sys.stderr)
            print(
                "\nRun 'python3 tools/generate_marketplace.py' to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"{len(plugins)} plugin(s); marketplace.json and REGISTRY.md are up to date.")
        return

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"  wrote {path.relative_to(REPO_ROOT)}")
    print(f"\n{len(plugins)} plugin(s) indexed.")


if __name__ == "__main__":
    main()
